# Generated by Django 5.0.4 on 2024-04-21 10:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_contactformlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 4, 21, 10, 0, 48, 904690, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(default='uploads/blogs/', upload_to='')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 4, 21, 10, 0, 48, 904690, tzinfo=datetime.timezone.utc))),
                ('content', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
    ]
